import { useEffect, useMemo, useState } from 'react';
import type { Account, Listing, OperationRecord, PriceTarget, SearchCriteria } from '@preco-certo/domain';
import { parsePrice, percentChange } from '@preco-certo/domain';
import { api } from './api';

type Step='search'|'review'|'result';
const money=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const key=(x:Listing)=>`${x.id}:${x.variationId??x.userProductId??''}`;

export function App(){
 const[theme,setTheme]=useState(localStorage.getItem('theme')??'dark'); const[accounts,setAccounts]=useState<Account[]>([]); const[query,setQuery]=useState('Capacete Norisk'); const[mode,setMode]=useState<'name'|'sku'|'list'>('name');
 const[criteria,setCriteria]=useState<SearchCriteria>({});const[items,setItems]=useState<Listing[]>([]);const[selected,setSelected]=useState<Set<string>>(new Set());const[price,setPrice]=useState('');const[step,setStep]=useState<Step>('search');const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[result,setResult]=useState<OperationRecord|null>(null);const[history,setHistory]=useState<OperationRecord[]>([]);const[tab,setTab]=useState<'operation'|'accounts'|'history'>('operation');
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('theme',theme)},[theme]);
 useEffect(()=>{api.accounts().then(setAccounts).catch(e=>setError(e.message));api.history().then(setHistory).catch(()=>{})},[]);
 const selectedItems=useMemo(()=>items.filter(x=>selected.has(key(x))),[items,selected]); const parsed=parsePrice(price);
 async function search(){setLoading(true);setError('');setSelected(new Set());setStep('search');const values=query.split(/[,\n]/).map(x=>x.trim()).filter(Boolean);const next:SearchCriteria=mode==='sku'?{skus:values}:mode==='list'?{names:values}:{query};setCriteria(next);try{setItems(await api.search(next))}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 function toggle(item:Listing){setSelected(prev=>{const n=new Set(prev);const k=key(item);n.has(k)?n.delete(k):n.add(k);return n})}
 function review(){if(parsed===null){setError('Informe um preço maior que zero, sem texto e com no máximo duas casas decimais.');return}if(!selectedItems.length){setError('Selecione ao menos um item.');return}setError('');setStep('review')}
 async function execute(){if(parsed===null)return;setLoading(true);setError('');const targets:PriceTarget[]=selectedItems.map(snapshot=>({snapshot,newPrice:parsed}));try{const r=await api.execute(criteria,targets);setResult(r.operation);setStep('result');setHistory(await api.history())}catch(e:any){if(e.data?.operation){setResult(e.data.operation);setStep('result');setHistory(await api.history())}else setError(e.message)}finally{setLoading(false)}}
 const blocking=(x:Listing)=>x.promotionActive?'Promoção ativa':x.automaticPricing?'Preço automático':x.state==='pending_migration'?'Migração pendente':'';
 return <div className="shell"><header><div><span className="logo">PC</span><strong>Preço Certo</strong><small>ambiente local · demonstração</small></div><button className="ghost" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?'☀ Tema claro':'☾ Tema escuro'}</button></header>
 <nav>{(['operation','accounts','history']as const).map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t==='operation'?'Alterar preços':t==='accounts'?'Contas':'Histórico'}</button>)}</nav>
 <main>{error&&<div className="alert error">{error}</div>}
 {tab==='accounts'&&<section><div className="heading"><div><p className="eyebrow">Etapa futura: OAuth individual</p><h1>Contas de vendedor</h1></div></div><div className="cards">{accounts.map(a=><article className="account" key={a.id}><span className={a.connected?'dot ok':'dot'}></span><div><b>{a.nickname}</b><p>seller_id {a.sellerId}</p><small>{a.connected?'Conectada ao gateway fictício':'Desconectada'} · conta DEMO</small></div><button disabled>Autorizar OAuth</button></article>)}</div><div className="alert">Credenciais e tokens ficarão exclusivamente no backend. Nenhuma conta real está configurada.</div></section>}
 {tab==='history'&&<section><div className="heading"><div><p className="eyebrow">SQLite local</p><h1>Histórico de operações</h1></div><button className="ghost" onClick={()=>api.history().then(setHistory)}>Atualizar</button></div>{!history.length?<div className="empty">Nenhuma operação registrada.</div>:history.map(op=><details className="history" key={op.id}><summary><span className={`pill ${op.status}`}>{op.status}</span><b>{new Date(op.createdAt).toLocaleString('pt-BR')}</b><span>{op.results.length} item(ns)</span></summary><p>{op.note} · responsável: {op.user}</p>{op.results.map((r,i)=><div className="history-row" key={i}><code>{r.snapshot.sku}</code><span>{money(r.snapshot.price)} → {money(r.intendedPrice)}</span><b>{r.status}: {r.message}</b></div>)}</details>)}</section>}
 {tab==='operation'&&<section><div className="steps"><span className={step==='search'?'on':''}>1 Pesquisa</span><i></i><span className={step==='review'?'on':''}>2 Revisão</span><i></i><span className={step==='result'?'on':''}>3 Resultado</span></div>
 {step==='search'&&<><div className="heading"><div><p className="eyebrow">Seleção granular, sem atualização automática</p><h1>Encontre os anúncios</h1></div></div><div className="searchbox"><div className="modes"><button className={mode==='name'?'active':''} onClick={()=>setMode('name')}>Nome ou modelo</button><button className={mode==='sku'?'active':''} onClick={()=>setMode('sku')}>SKU exato</button><button className={mode==='list'?'active':''} onClick={()=>setMode('list')}>Lista</button></div><textarea value={query} onChange={e=>setQuery(e.target.value)} placeholder={mode==='list'?'Um nome por linha ou separado por vírgula':'Digite para pesquisar'}/><button className="primary" onClick={search} disabled={loading}>{loading?'Pesquisando…':'Pesquisar'}</button></div>
 {!!items.length&&<><div className="results-head"><div><b>{items.length} combinações encontradas</b><small>Nenhuma é selecionada automaticamente.</small></div><span>{selected.size} selecionada(s)</span></div><div className="table-wrap"><table><thead><tr><th></th><th>Conta / anúncio</th><th>SKU</th><th>Variação</th><th>Estrutura</th><th>Preço</th><th>Estado</th></tr></thead><tbody>{items.map(x=>{const block=blocking(x);return <tr className={block?'blocked':''} key={key(x)}><td><input aria-label={`Selecionar ${x.sku}`} type="checkbox" checked={selected.has(key(x))} onChange={()=>toggle(x)}/></td><td><b>{x.title}</b><small>{accounts.find(a=>a.id===x.accountId)?.nickname} · {x.id}</small></td><td><code>{x.sku}</code></td><td>{x.size} · {x.color}</td><td><span className="pill">{x.structure==='traditional'?'Tradicional':'User Product'}</span></td><td><b>{money(x.price)}</b></td><td>{block?<span className="warning">⚠ {block}</span>:<span className="success">Ativo</span>}</td></tr>})}</tbody></table></div><div className="pricebar"><div><label>Novo preço único</label><input value={price} onChange={e=>setPrice(e.target.value)} inputMode="decimal" placeholder="0,00"/><small>Regra deste produto: todos os selecionados recebem o mesmo novo preço.</small></div><div className="summary"><span>{selectedItems.length} item(ns)</span><b>{parsed&&selectedItems[0]?`${percentChange(selectedItems[0].price,parsed)>0?'+':''}${percentChange(selectedItems[0].price,parsed)}%`:'—'}</b></div><button className="primary" onClick={review}>Revisar alteração</button></div></>}{!loading&&!items.length&&<div className="empty">Pesquise “Capacete Norisk” para ver a massa de demonstração.</div>}</>}
 {step==='review'&&<><div className="heading"><div><p className="eyebrow">Confirmação explícita obrigatória</p><h1>Revise antes de simular</h1></div><button className="ghost" onClick={()=>setStep('search')}>← Voltar e editar</button></div><div className="alert">Segunda checagem será feita no servidor imediatamente antes da execução. Esta operação é simulada e não envia nada ao Mercado Livre.</div><div className="review-grid"><article><small>Itens afetados</small><strong>{selectedItems.length}</strong></article><article><small>Contas afetadas</small><strong>{new Set(selectedItems.map(x=>x.accountId)).size}</strong></article><article><small>Novo preço único</small><strong>{money(parsed!)}</strong></article></div><div className="table-wrap"><table><thead><tr><th>Anúncio</th><th>Conta</th><th>SKU / variação</th><th>Anterior</th><th>Novo</th><th>Reajuste</th></tr></thead><tbody>{selectedItems.map(x=><tr key={key(x)}><td>{x.id}<small>{x.title}</small></td><td>{accounts.find(a=>a.id===x.accountId)?.nickname}</td><td><code>{x.sku}</code><small>{x.size} · {x.color}</small></td><td>{money(x.price)}</td><td><b>{money(parsed!)}</b></td><td>{percentChange(x.price,parsed!)}%</td></tr>)}</tbody></table></div><div className="approval"><p><b>Ao confirmar, aprovo exatamente os itens e valores acima.</b><br/><small>Itens bloqueados serão registrados individualmente; não haverá falso sucesso global.</small></p><button className="danger" disabled={loading} onClick={execute}>{loading?'Verificando…':'Confirmar e executar simulação'}</button></div></>}
 {step==='result'&&result&&<><div className="heading"><div><p className="eyebrow">Operação {result.id}</p><h1>{result.status==='simulated'?'Simulação concluída':'Operação bloqueada'}</h1></div></div><div className={`alert ${result.status==='blocked'?'error':'successbox'}`}>{result.note}</div>{result.results.map((r,i)=><article className="result" key={i}><span className={`pill ${r.status}`}>{r.status}</span><div><b>{r.snapshot.title}</b><small>{r.snapshot.id} · {r.snapshot.sku} · {r.snapshot.size}/{r.snapshot.color}</small></div><div>{money(r.snapshot.price)} → <b>{money(r.intendedPrice)}</b></div><p>{r.message}</p></article>)}<button className="primary" onClick={()=>{setStep('search');setSelected(new Set());setPrice('')}}>Nova operação</button></>}
 </section>}</main><footer>Preço Certo v0.1 · dados fictícios · API local em 127.0.0.1</footer></div>
}
