import { afterEach,describe,expect,it } from 'vitest';
import { buildApp } from './app.js';import { HistoryRepository } from './history.js';import { listings,MockMarketplaceGateway,type PriceTarget } from '@preco-certo/domain';
const apps:any[]=[];afterEach(async()=>{await Promise.all(apps.splice(0).map(a=>a.close()))});
function setup(gateway=new MockMarketplaceGateway()){const app=buildApp({gateway,history:new HistoryRepository(':memory:'),appUser:'teste'});apps.push(app);return app}
describe('API',()=>{
 it('persiste simulação detalhada',async()=>{const app=setup();const targets:PriceTarget[]=[{snapshot:listings[0],newPrice:500}];const res=await app.inject({method:'POST',url:'/api/operations/execute',payload:{criteria:{query:'Force'},targets,approved:true}});expect(res.statusCode).toBe(200);const history=await app.inject({method:'GET',url:'/api/history'});expect(history.json()[0].note).toContain('nenhum envio');expect(history.json()[0].results[0].snapshot.sku).toBe(listings[0].sku)});
 it('persiste bloqueio e motivo',async()=>{const app=setup();const res=await app.inject({method:'POST',url:'/api/operations/execute',payload:{criteria:{},targets:[{snapshot:listings[1],newPrice:500}],approved:true}});expect(res.statusCode).toBe(409);expect(res.json().issues[0].reason).toBe('active_promotion');expect((await app.inject({method:'GET',url:'/api/history'})).json()[0].status).toBe('blocked')});
 it('não informa sucesso global diante de falha individual',async()=>{class FailureGateway extends MockMarketplaceGateway{override async updatePrices(t:PriceTarget[]){return t.map((x,i)=>({itemId:x.snapshot.id,status:(i?'failed':'simulated') as 'failed'|'simulated',message:i?'falha simulada':'ok'}))}}const app=setup(new FailureGateway());const targets=[{snapshot:listings[3],newPrice:550},{snapshot:listings[4],newPrice:550},{snapshot:listings[5],newPrice:550}];const res=await app.inject({method:'POST',url:'/api/operations/execute',payload:{criteria:{},targets,approved:true}});expect(res.json().operation.status).toBe('partial_failure')});
 it('não expõe segredos no health check',async()=>{process.env.ML_CLIENT_SECRET='super-secreto';const body=(await setup().inject({method:'GET',url:'/health'})).body;expect(body).not.toContain('super-secreto');expect(body).not.toContain('token')});
});
